# Generated by Django 4.2.8 on 2023-12-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familleproduit',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
