# Generated by Django 4.2.8 on 2023-12-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0004_prix_point_vente_produit_code_alter_pointdevente_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='code',
            field=models.CharField(default='le code du panier par défaut', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_creation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
