# Generated by Django 4.2.8 on 2023-12-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0005_panier_code_alter_produit_date_creation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointdevente',
            old_name='nom',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='pointdevente',
            old_name='gps',
            new_name='commune',
        ),
        migrations.RenameField(
            model_name='pointdevente',
            old_name='village',
            new_name='gps_long',
        ),
        migrations.RemoveField(
            model_name='pointdevente',
            name='adresse',
        ),
        migrations.AddField(
            model_name='pointdevente',
            name='gps_lat',
            field=models.CharField(default=23, max_length=225),
        ),
    ]
