# Generated by Django 4.2.8 on 2023-12-26 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0007_alter_pointdevente_gps_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier_Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('ponderation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nom', models.CharField(default='Adresse par défaut', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='panier',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='quantite',
        ),
        migrations.AddField(
            model_name='panier',
            name='label',
            field=models.CharField(default='Label par défaut', max_length=100),
        ),
        migrations.AlterField(
            model_name='panier',
            name='date_ajout',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Ponderation',
        ),
        migrations.AddField(
            model_name='panier_produit',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansade_app.panier'),
        ),
        migrations.AddField(
            model_name='panier_produit',
            name='prix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ansade_app.prix'),
        ),
    ]
