# Generated by Django 4.2 on 2023-12-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0008_panier_produit_remove_panier_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='date_ajout',
            field=models.DateField(),
        ),
    ]
